test "pepita.comerAlpiste(0) debería fallar" {
  assert.throwsException({ pepita.comerAlpiste(0) })
}

test "pepita.comerAlpiste(-10) debería fallar" {
  assert.throwsException({ pepita.comerAlpiste(-10) })
}

test "pepita.comerAlpiste(-10) debería lanzar un mensaje de error expresivo" {
 try {
   pepita.comerAlpiste(-10)
 } catch e : Exception {
   assert.that(["positiv", "negativ", "cantidad", "menor", "cero", "0", "-10"].any { 
        it =>  e.message().toLowerCase()
                   .contains(it) })
 }
}


test "pepita.comerAlpiste(10) NO debería fallar" {
  const energiaInicial = pepita.energia()
  pepita.comerAlpiste(10)
  assert.that(pepita.energia() > energiaInicial)
}
